### ISSUE TITLE
Where can I find the colorscheme.conf file for Horizon? 

### ISSUE THREAD

**Issue by garret** [zodd18/dotfiles#1]
I cannot find in your repo the terminal color scheme for Horizon. It should be in a file called colorscheme.conf according to your kitty.conf but it is not in that folder.

**Comment by zodd18** [comment]
Sorry for the delay, it's right [here](https://github.com/zodd18/dotfiles/tree/master/themes/Horizon/.config/kitty).
kitty.conf is shared among my other rices, that's why it's in global-config. Otherwise I'd have to have a kitty.conf for each rice and maintain them all at the same time whenever I want to change something. 
On the other hand, the colorscheme it's the only thing that's different among the rices, that's why I got colorscheme.conf for each rice in their respective kitty config.
